sudo :required
services:
  - docker
before_instal:
  - docker build -t anmol4developers/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true anmol4developers/docker-react npm rum test  -- -- coverage

